### ISSUE TITLE
Automatic database startup

### ISSUE THREAD

**Issue by junrui-liu** [textproclab/lore-server#2]
- Implement automatic startup of database when a container is created, e.g. by writing a small bash script and set it as the `ENTRYPOINT`.
- Similarly, implement automatic shutdown to keep the db clean and consistent.

**Comment by jgordon** [comment]
Is it necessary to shutdown the DB? The Docker container should be stateless.

**Comment by junrui-liu** [comment]
No, it isn't necessary. Thanks for the suggestion!
